version: 2
workflow:
  test
jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  build_and_test:
    jobs:
      - plan-apply